# Generated by Django 3.1.4 on 2021-01-03 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('content', models.TextField(default='', verbose_name='Content')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Is Anonymous')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('views_number', models.IntegerField(default=0, verbose_name='Views number')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is private')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Is locked')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('viewers', models.ManyToManyField(blank=True, related_name='_note_viewers_+', to=settings.AUTH_USER_MODEL, verbose_name='Viewers')),
            ],
        ),
    ]
